package constants

var Categories = []string{
	"CONFESSION", "EXPOSURE", "SECRETS", "JUDGMENT", "REGRET",
	"GUILT", "TRUTH", "ACCUSATION", "SUSPICION", "REPUTATION",

	"CRUSH", "JEALOUSY", "BETRAYAL", "INFIDELITY", "COMPARISON",
	"REJECTION", "DESPERATION", "VALIDATION", "INSECURITY", "APPROVAL",

	"HYPOCRISY", "FAKE", "PRETENCE", "LIE", "BACKSTAB",
	"RUMOR", "DRAMA", "BIAS", "FAVORITISM", "GRUDGE",

	"PROJECTION", "DENIAL", "DELUSION", "OBSESSION", "CONTROL",
	"MANIPULATION", "POWER", "WEAKNESS", "FEAR", "SHAME",

	"CANCELLED", "PROBLEMATIC", "UNFILTERED", "SAVAGE", "BRUTAL",
	"MESSY", "PETTY", "TOXIC", "UNHINGED", "CURSED",
}
