package questions

import "anonymity/models"

// GetDefaultQuestions returns a new slice of 100 funny party game questions.
// Callers can safely shuffle the returned slice without affecting other callers.
func GetDefaultQuestions() []models.Question {
	return []models.Question{
		{ID: "q001", Template: "If {player} could only eat one food for the rest of their life, what would they choose and why would it be a terrible idea?", Category: "food"},
		{ID: "q002", Template: "What embarrassing childhood phase did {player} definitely go through that they'll never admit to?", Category: "embarrassing"},
		{ID: "q003", Template: "What useless superpower would {player} accidentally misuse and cause chaos with?", Category: "superpower"},
		{ID: "q004", Template: "If {player} wrote a tell-all autobiography, what would the most scandalous chapter be titled?", Category: "autobiography"},
		{ID: "q005", Template: "What excuse would {player} give if they showed up 3 hours late to their own wedding?", Category: "excuse"},
		{ID: "q006", Template: "What animal would {player} be reincarnated as, and what would their first thought be?", Category: "animal"},
		{ID: "q007", Template: "If {player} had to go on a blind date with a celebrity, who would be the worst possible match?", Category: "dating"},
		{ID: "q008", Template: "What would {player}'s job title be if they worked at a company that only hired people based on their worst habits?", Category: "work"},
		{ID: "q009", Template: "What would {player}'s signature dance move be at a wedding when they've had one too many?", Category: "party"},
		{ID: "q010", Template: "What fashion trend from the past would {player} bring back and insist was 'totally cool'?", Category: "fashion"},
		{ID: "q011", Template: "What movie would {player} ruin by being cast as the lead role?", Category: "movie"},
		{ID: "q012", Template: "If {player} committed a victimless crime, what would it be and what would their alibi be?", Category: "crime"},
		{ID: "q013", Template: "In a zombie apocalypse, what would {player}'s survival strategy be and why would it fail immediately?", Category: "zombie"},
		{ID: "q014", Template: "If aliens abducted {player}, what would they report back to their home planet about humanity?", Category: "aliens"},
		{ID: "q015", Template: "If {player} became a billionaire overnight, what would be the first ridiculous thing they'd buy?", Category: "billionaire"},
		{ID: "q016", Template: "What reality TV show would {player} be cast on and what would get them eliminated first?", Category: "reality_tv"},
		{ID: "q017", Template: "If {player} could time travel, what minor historical event would they accidentally mess up?", Category: "time_travel"},
		{ID: "q018", Template: "What hypothetical question would {player} overthink so badly they'd need to lie down?", Category: "hypothetical"},
		{ID: "q019", Template: "What secret talent does {player} have that they're weirdly proud of but would never perform in public?", Category: "talent"},
		{ID: "q020", Template: "What's the most random thing {player} has ever Googled at 3 AM?", Category: "random"},
		{ID: "q021", Template: "If {player} had to survive on a deserted island with one person from this room, who would they pick and what would drive them apart?", Category: "hypothetical"},
		{ID: "q022", Template: "What embarrassing thing would {player} do to impress their crush that would backfire spectacularly?", Category: "embarrassing"},
		{ID: "q023", Template: "What talent show act would {player} perform that would get them buzzed off in 5 seconds?", Category: "talent"},
		{ID: "q024", Template: "What would the opening line of {player}'s memoir be?", Category: "autobiography"},
		{ID: "q025", Template: "What excuse would {player} use when caught singing in the shower by a neighbor?", Category: "excuse"},
		{ID: "q026", Template: "If {player} could only communicate through animal sounds for a week, which animal would they choose and why would it go wrong?", Category: "animal"},
		{ID: "q027", Template: "What would {player}'s dating profile say that would attract only the wrong people?", Category: "dating"},
		{ID: "q028", Template: "What would {player}'s resignation letter say if they quit their job in the most dramatic way possible?", Category: "work"},
		{ID: "q029", Template: "What would {player} do at a party that would make everyone slowly back away?", Category: "party"},
		{ID: "q030", Template: "What outfit would {player} wear to a formal event that would cause a fashion emergency?", Category: "fashion"},
		{ID: "q031", Template: "What movie scene would {player} ruin by laughing at the wrong moment?", Category: "movie"},
		{ID: "q032", Template: "If {player} had to plan the perfect heist, what would their role be and how would they mess it up?", Category: "crime"},
		{ID: "q033", Template: "What would {player}'s zombie survival weapon of choice be and why would it be useless?", Category: "zombie"},
		{ID: "q034", Template: "What would aliens find most confusing about {player} after observing them for a day?", Category: "aliens"},
		{ID: "q035", Template: "If {player} had a billion dollars, what charity would they accidentally insult while trying to donate?", Category: "billionaire"},
		{ID: "q036", Template: "What would {player}'s catchphrase be on a reality show that would become a meme for all the wrong reasons?", Category: "reality_tv"},
		{ID: "q037", Template: "What moment in history would {player} travel back to and accidentally make worse?", Category: "time_travel"},
		{ID: "q038", Template: "If {player} could swap lives with anyone for a day, who would they pick and what would go horribly wrong?", Category: "hypothetical"},
		{ID: "q039", Template: "What embarrassing karaoke song would {player} absolutely nail and then regret forever?", Category: "embarrassing"},
		{ID: "q040", Template: "What useless skill would {player} spend 10,000 hours mastering?", Category: "talent"},
		{ID: "q041", Template: "What would the dedication page of {player}'s book say that would offend everyone?", Category: "autobiography"},
		{ID: "q042", Template: "What excuse would {player} give when their phone autocorrects something embarrassing in a group chat?", Category: "excuse"},
		{ID: "q043", Template: "If {player} had to fight a bear, what would their strategy be and what would their last words be?", Category: "animal"},
		{ID: "q044", Template: "What would {player}'s ideal first date be that would actually be a disaster?", Category: "dating"},
		{ID: "q045", Template: "What would {player}'s LinkedIn headline say if they were 100% honest?", Category: "work"},
		{ID: "q046", Template: "What would {player} bring to a potluck that would make everyone suspicious?", Category: "party"},
		{ID: "q047", Template: "What fashion rule would {player} break that would cause a stylist to have a breakdown?", Category: "fashion"},
		{ID: "q048", Template: "What movie would {player} spoil within the first 5 minutes of watching it with someone?", Category: "movie"},
		{ID: "q049", Template: "If {player} had to hide evidence, where would they put it that would be found immediately?", Category: "crime"},
		{ID: "q050", Template: "What would {player}'s zombie apocalypse group role be and why would the group vote them out first?", Category: "zombie"},
		{ID: "q051", Template: "What would aliens assume about all humans based solely on observing {player}?", Category: "aliens"},
		{ID: "q052", Template: "If {player} became a billionaire, what would their most tone-deaf purchase be?", Category: "billionaire"},
		{ID: "q053", Template: "What reality TV challenge would {player} fail in the most humiliating way?", Category: "reality_tv"},
		{ID: "q054", Template: "What would {player} say to their past self that would create a paradox?", Category: "time_travel"},
		{ID: "q055", Template: "If {player} could have dinner with any historical figure, who would they pick and what awkward thing would they say?", Category: "hypothetical"},
		{ID: "q056", Template: "What embarrassing thing would {player} do to get a discount at a store?", Category: "embarrassing"},
		{ID: "q057", Template: "What talent would {player} claim to have on their resume that would be exposed in the first week?", Category: "talent"},
		{ID: "q058", Template: "What would the blurb on the back of {player}'s book say that would make no one want to read it?", Category: "autobiography"},
		{ID: "q059", Template: "What excuse would {player} give when they forget someone's name at a party?", Category: "excuse"},
		{ID: "q060", Template: "If {player} could be reincarnated as a food, what would they be and what would happen to them?", Category: "food"},
		{ID: "q061", Template: "What would {player}'s spirit animal be based on their worst habits?", Category: "animal"},
		{ID: "q062", Template: "What would {player}'s breakup line be that would go viral for being terrible?", Category: "dating"},
		{ID: "q063", Template: "What would {player}'s out-of-office message say if they were completely honest?", Category: "work"},
		{ID: "q064", Template: "What would {player} do at a karaoke night that would clear the room?", Category: "party"},
		{ID: "q065", Template: "What outfit would {player} wear to a job interview that would guarantee they don't get the job?", Category: "fashion"},
		{ID: "q066", Template: "What movie would {player} remake and completely ruin with their 'creative vision'?", Category: "movie"},
		{ID: "q067", Template: "If {player} had to pull off one small crime, what would they do and how would they get caught?", Category: "crime"},
		{ID: "q068", Template: "What would {player}'s zombie survival base be and why would it be overrun in 24 hours?", Category: "zombie"},
		{ID: "q069", Template: "What would aliens name {player} when they add them to their 'Earth specimens' collection?", Category: "aliens"},
		{ID: "q070", Template: "If {player} had unlimited money, what would be the first thing they'd do that would get them cancelled?", Category: "billionaire"},
		{ID: "q071", Template: "What would {player}'s villain arc be on a reality TV show?", Category: "reality_tv"},
		{ID: "q072", Template: "What would {player} change about their past that would somehow make the present worse?", Category: "time_travel"},
		{ID: "q073", Template: "If {player} could only keep one app on their phone forever, which would they choose and why would it be a mistake?", Category: "hypothetical"},
		{ID: "q074", Template: "What embarrassing moment would {player} relive if they could, and what would they do differently (that would still fail)?", Category: "embarrassing"},
		{ID: "q075", Template: "What hidden talent would {player} reveal at a talent show that would confuse everyone?", Category: "talent"},
		{ID: "q076", Template: "What would {player}'s book tour be like and what city would ban them first?", Category: "autobiography"},
		{ID: "q077", Template: "What excuse would {player} give when they're caught talking to themselves?", Category: "excuse"},
		{ID: "q078", Template: "If {player} had to create a new flavor of chips, what would it be and why would it be recalled?", Category: "food"},
		{ID: "q079", Template: "What would {player} do if they could talk to animals for one day and what would go wrong?", Category: "animal"},
		{ID: "q080", Template: "What would {player}'s love language be based on their most annoying habits?", Category: "dating"},
		{ID: "q081", Template: "What would {player}'s performance review say if their boss was 100% honest?", Category: "work"},
		{ID: "q082", Template: "What would {player}'s party trick be that would make everyone uncomfortable?", Category: "party"},
		{ID: "q083", Template: "What fashion trend would {player} start that would never catch on?", Category: "fashion"},
		{ID: "q084", Template: "What movie genre would {player} claim to hate but secretly love?", Category: "movie"},
		{ID: "q085", Template: "If {player} had to be a criminal mastermind, what would their weakness be that would lead to their capture?", Category: "crime"},
		{ID: "q086", Template: "What would {player}'s zombie survival team name be and why would everyone refuse to join?", Category: "zombie"},
		{ID: "q087", Template: "What would aliens conclude about human emotions after studying {player}?", Category: "aliens"},
		{ID: "q088", Template: "If {player} could buy one island, what would they name it and what would they do there that would get them in trouble?", Category: "billionaire"},
		{ID: "q089", Template: "What would {player}'s strategy be on a dating reality show that would get them sent home first?", Category: "reality_tv"},
		{ID: "q090", Template: "What would {player} tell their 10-year-old self that would traumatize them?", Category: "time_travel"},
		{ID: "q091", Template: "If {player} could only listen to one song for the rest of their life, what would they pick and how would it drive them insane?", Category: "hypothetical"},
		{ID: "q092", Template: "What embarrassing thing would {player} do to win an argument?", Category: "embarrassing"},
		{ID: "q093", Template: "What talent would {player} discover they have at the worst possible moment?", Category: "talent"},
		{ID: "q094", Template: "What would {player}'s Wikipedia page say if it was written by their enemies?", Category: "autobiography"},
		{ID: "q095", Template: "What excuse would {player} give when they show up to the wrong party?", Category: "excuse"},
		{ID: "q096", Template: "If {player} could only eat at one restaurant forever, which would they choose and what would eventually happen?", Category: "food"},
		{ID: "q097", Template: "What would {player}'s superpower be if it was based on their biggest flaw?", Category: "superpower"},
		{ID: "q098", Template: "What random object would {player} be buried with and why would it confuse archaeologists?", Category: "random"},
		{ID: "q099", Template: "If {player} could only use one emoji for the rest of their life, which would they choose and how would it backfire?", Category: "random"},
		{ID: "q100", Template: "What would {player}'s last words be if they were being dramatic about something minor?", Category: "random"},
	}
}
